src/segmentation_services/arm_filter_srv.cpp File Reference
#include <ros/ros.h>
*
#include <tf/transform_listener.h>
*
#include <tf/transform_broadcaster.h>
*
#include <sensor_msgs/PointCloud2.h>
*
#include <pcl_conversions/pcl_conversions.h>
*
#include <pcl_ros/point_cloud.h>
*
#include <pcl_ros/filters/crop_box.h>
*
#include `../point_cloud_library/pc_manager.h`
*
#include `../point_cloud_library/srv_manager.h`
*
#include <pitt_msgs/ArmFilter.h>
*
#include <boost/thread.hpp>
*
#include <boost/thread/mutex.hpp>
*
Functions
PCLCloudPtr inputCloud (new PCLCloud)
PCLCloudPtr outputCloud1 (new PCLCloud)
PCLCloudPtr outputCloud2 (new PCLCloud)
PCLCloudPtr outputCloud3 (new PCLCloud)
PCLCloudPtr outputCloud4 (new PCLCloud)
void visSpin ()
PCLCloudPtr armFiltering (PCLCloudPtr original, Vector4f minValues, Vector4f maxValues, StampedTransform frame)
Vector4f generateBoxVector (vector< float > vec)
bool filter (ArmFilterRequest &input, ArmFilterResponse &output)
int main (int argc, char **argv)
Variables
const float DEFAULT_PARAM_ARM_SRV_MIN_FOREARM_BOX [] = { -0.040f, -0.120f, -0.190f}
const float DEFAULT_PARAM_ARM_SRV_MAX_FOREARM_BOX [] = { 0.340f, 0.120f, 0.105f}
const float DEFAULT_PARAM_ARM_SRV_MIN_ELBOW_BOX [] = { -0.090f, -0.135f, -0.160f}
const float DEFAULT_PARAM_ARM_SRV_MAX_ELBOW_BOX [] = { 0.440f, 0.135f, 0.110f}
const Duration WAIT_FOR_TF_TIME_OUT = Duration(srvm::DEFAULT_TF_WAIT_SECONDS)
StampedTransform leftForearmCameraTansf
StampedTransform rightForearmCameraTansf
StampedTransform leftElbowCameraTansf
StampedTransform rightElbowCameraTansf
bool tfError = false
bool showClouds
boost::shared_ptr
*
< visualization::PCLVisualizer > vis
boost::thread vis_thread
boost::mutex vis_mutex
string log_str_depth = `Loading...`
Function Documentation
PCLCloudPtr armFiltering (PCLCloudPtr original, Vector4f minValues, Vector4f maxValues, StampedTransform frame)
Definition at line 66 of file arm_filter_srv.cpp.
Referenced by filter().
bool filter (ArmFilterRequest & input, ArmFilterResponse & output)
Definition at line 112 of file arm_filter_srv.cpp.
References armFiltering(), DEFAULT_PARAM_ARM_SRV_MAX_ELBOW_BOX, DEFAULT_PARAM_ARM_SRV_MAX_FOREARM_BOX, DEFAULT_PARAM_ARM_SRV_MIN_ELBOW_BOX, DEFAULT_PARAM_ARM_SRV_MIN_FOREARM_BOX, generateBoxVector(), srvm::getArrayToPrint(), srvm::getService3DArrayParameter(), inputCloud(), leftElbowCameraTansf, leftForearmCameraTansf, log_str_depth, outputCloud1(), outputCloud2(), outputCloud3(), outputCloud4(), rightElbowCameraTansf, rightForearmCameraTansf, showClouds, tfError, vis, and vis_mutex.
Referenced by main().
Vector4f generateBoxVector (vector< float > vec)
Definition at line 105 of file arm_filter_srv.cpp.
Referenced by filter().
PCLCloudPtr inputCloud (new PCLCloud)
Referenced by filter().
int main (int argc, char ** argv)
Definition at line 183 of file arm_filter_srv.cpp.
References srvm::DEFAULT_PARAM_ARM_SRV_CAMERA_FRAME, srvm::DEFAULT_PARAM_ARM_SRV_LEFT_ELBOW_FRAME, srvm::DEFAULT_PARAM_ARM_SRV_LEFT_FOREARM_FRAME, srvm::DEFAULT_PARAM_ARM_SRV_RIGHT_ELBOW_FRAME, srvm::DEFAULT_PARAM_ARM_SRV_RIGHT_FOREARM_FRAME, srvm::DEFAULT_PARAM_ARM_SRV_SHOW_CLOUDS, filter(), srvm::getBoolPtrParameter(), srvm::getStringPtrParameter(), leftElbowCameraTansf, leftForearmCameraTansf, log_str_depth, rightElbowCameraTansf, rightForearmCameraTansf, showClouds, srvm::SRV_NAME_ARM_FILTER, tfError, vis, vis_thread, visSpin(), and WAIT_FOR_TF_TIME_OUT.
PCLCloudPtr outputCloud1 (new PCLCloud)
Referenced by filter().
PCLCloudPtr outputCloud2 (new PCLCloud)
Referenced by filter().
PCLCloudPtr outputCloud3 (new PCLCloud)
Referenced by filter().
PCLCloudPtr outputCloud4 (new PCLCloud)
Referenced by filter().
void visSpin ()
Definition at line 57 of file arm_filter_srv.cpp.
References vis, and vis_mutex.
Referenced by main().
Variable Documentation
const float DEFAULT_PARAM_ARM_SRV_MAX_ELBOW_BOX[] = { 0.440f, 0.135f, 0.110f}
Definition at line 35 of file arm_filter_srv.cpp.
Referenced by filter().
const float DEFAULT_PARAM_ARM_SRV_MAX_FOREARM_BOX[] = { 0.340f, 0.120f, 0.105f}
Definition at line 33 of file arm_filter_srv.cpp.
Referenced by filter().
const float DEFAULT_PARAM_ARM_SRV_MIN_ELBOW_BOX[] = { -0.090f, -0.135f, -0.160f}
Definition at line 34 of file arm_filter_srv.cpp.
Referenced by filter().
const float DEFAULT_PARAM_ARM_SRV_MIN_FOREARM_BOX[] = { -0.040f, -0.120f, -0.190f}
Definition at line 32 of file arm_filter_srv.cpp.
Referenced by filter().
StampedTransform leftElbowCameraTansf
Definition at line 40 of file arm_filter_srv.cpp.
Referenced by filter(), and main().
StampedTransform leftForearmCameraTansf
Definition at line 40 of file arm_filter_srv.cpp.
Referenced by filter(), and main().
string log_str_depth = `Loading...`
Definition at line 49 of file arm_filter_srv.cpp.
Referenced by filter(), and main().
StampedTransform rightElbowCameraTansf
Definition at line 40 of file arm_filter_srv.cpp.
Referenced by filter(), and main().
StampedTransform rightForearmCameraTansf
Definition at line 40 of file arm_filter_srv.cpp.
Referenced by filter(), and main().
bool showClouds
Definition at line 44 of file arm_filter_srv.cpp.
Referenced by filter(), and main().
bool tfError = false
Definition at line 43 of file arm_filter_srv.cpp.
Referenced by filter(), and main().
boost::shared_ptr< visualization::PCLVisualizer> vis
Definition at line 46 of file arm_filter_srv.cpp.
Referenced by filter(), main(), and visSpin().
boost::mutex vis_mutex
Definition at line 48 of file arm_filter_srv.cpp.
Referenced by filter(), and visSpin().
boost::thread vis_thread
Definition at line 47 of file arm_filter_srv.cpp.
Referenced by main().
const Duration WAIT_FOR_TF_TIME_OUT = Duration(srvm::DEFAULT_TF_WAIT_SECONDS)
Definition at line 37 of file arm_filter_srv.cpp.
Referenced by main().