src/segmentation_services/cluster_segmentation_srv.cpp File Reference
#include `ros/ros.h`
*
#include <iostream>
*
#include `pitt_msgs/ClusterSegmentation.h`
*
#include `pitt_msgs/InliersCluster.h`
*
#include <pcl_ros/point_cloud.h>
*
#include <pcl/segmentation/extract_clusters.h>
*
#include <std_msgs/String.h>
*
#include <pcl_conversions/pcl_conversions.h>
*
#include `../point_cloud_library/pc_manager.h`
*
#include `../point_cloud_library/srv_manager.h`
*
Functions
bool clusterize (ClusterSegmentation::Request &req, ClusterSegmentation::Response &res)
int main (int argc, char **argv)
Variables
ros::NodeHandle * nh_ptr = NULL
const double CLUSTER_TOLERANCE_DEFAULT = 0.03
const double CLUSTER_MIN_RATE_DEFAULT = 0.01
const double CLUSTER_MAX_RATE_DEFAULT = 0.99
const int CLUSTER_MIN_INPUT_SIZE_DEFAULT = 30
Function Documentation
bool clusterize (ClusterSegmentation::Request & req, ClusterSegmentation::Response & res)
Definition at line 38 of file cluster_segmentation_srv.cpp.
References pcm::PCManager::cloudForRosMsg(), CLUSTER_MAX_RATE_DEFAULT, CLUSTER_MIN_INPUT_SIZE_DEFAULT, CLUSTER_MIN_RATE_DEFAULT, CLUSTER_TOLERANCE_DEFAULT, nh_ptr, srvm::PARAM_NAME_CLUSTER_MAX_RATE, srvm::PARAM_NAME_CLUSTER_MIN_RATE, srvm::PARAM_NAME_CLUSTER_TOLERANCE, and pcm::tree().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 114 of file cluster_segmentation_srv.cpp.
References clusterize(), nh_ptr, and srvm::SRV_NAME_CUSTER_FILTER.
Variable Documentation
const double CLUSTER_MAX_RATE_DEFAULT = 0.99
Definition at line 34 of file cluster_segmentation_srv.cpp.
Referenced by clusterize().
const int CLUSTER_MIN_INPUT_SIZE_DEFAULT = 30
Definition at line 35 of file cluster_segmentation_srv.cpp.
Referenced by clusterize().
const double CLUSTER_MIN_RATE_DEFAULT = 0.01
Definition at line 33 of file cluster_segmentation_srv.cpp.
Referenced by clusterize().
const double CLUSTER_TOLERANCE_DEFAULT = 0.03
Definition at line 32 of file cluster_segmentation_srv.cpp.
Referenced by clusterize().
ros::NodeHandle* nh_ptr = NULL
Definition at line 29 of file cluster_segmentation_srv.cpp.
Referenced by clusterize(), and main().