src/segmentation_services/cone_segmentation_srv.cpp File Reference
#include `ros/ros.h`
*
#include <pcl_ros/point_cloud.h>
*
#include <pcl/segmentation/sac_segmentation.h>
*
#include `pitt_msgs/PrimitiveSegmentation.h`
*
#include `../point_cloud_library/pc_manager.h`
*
#include `../point_cloud_library/srv_manager.h`
*
#include <boost/thread.hpp>
*
#include <boost/thread/mutex.hpp>
*
#include <boost/format.hpp>
*
Classes
struct vector3d
Functions
void visSpin ()
vector3d getNormalizeAxesDirectionVector (ModelCoefficients::Ptr coefficients)
vector3d getPointOnAxes (ModelCoefficients::Ptr coefficients, vector3d direction, float t)
vector3d getVectorBetweenPoints (vector3d p1, vector3d p2)
bool ransacConeDetaction (PrimitiveSegmentation::Request &req, PrimitiveSegmentation::Response &res)
int main (int argc, char **argv)
Variables
ros::NodeHandle * nh_ptr = NULL
static const double CONE_NORMAL_DISTANCE_WEIGTH = 0.0006
static const double CONE_DISTANCE_TH = 0.0055
static const double CONE_MIN_RADIUS_LIMIT = 0.001
static const double CONE_MAX_RADIUS_LIMIT = 0.500
static const int CONE_MAX_ITERATION_LIMIT = 1000
static const double CONE_EPS_ANGLE_TH = 0.4
static const double CONE_MIN_OPENING_ANGLE_DEGREE = 10.0
static const double CONE_MAX_OPENING_ANGLE_DEGREE = 170.0
const bool VISUALIZE_RESULT = false
boost::shared_ptr
*
< visualization::PCLVisualizer > vis
boost::thread vis_thread
boost::mutex vis_mutex
Function Documentation
vector3d getNormalizeAxesDirectionVector (ModelCoefficients::Ptr coefficients)
Definition at line 54 of file cone_segmentation_srv.cpp.
References vector3d::x, vector3d::y, and vector3d::z.
Referenced by ransacConeDetaction().
vector3d getPointOnAxes (ModelCoefficients::Ptr coefficients, vector3d direction, float t)
Definition at line 65 of file cone_segmentation_srv.cpp.
References vector3d::x, vector3d::y, and vector3d::z.
Referenced by ransacConeDetaction().
vector3d getVectorBetweenPoints (vector3d p1, vector3d p2)
Definition at line 74 of file cone_segmentation_srv.cpp.
References vector3d::x, vector3d::y, and vector3d::z.
Referenced by ransacConeDetaction().
int main (int argc, char ** argv)
Definition at line 220 of file cone_segmentation_srv.cpp.
References pcm::PCManager::createVisor(), nh_ptr, ransacConeDetaction(), srvm::SRV_NAME_RANSAC_CONE_FILTER, vis, vis_thread, visSpin(), and VISUALIZE_RESULT.
bool ransacConeDetaction (PrimitiveSegmentation::Request & req, PrimitiveSegmentation::Response & res)
Definition at line 83 of file cone_segmentation_srv.cpp.
References pcm::PCManager::cloudForRosMsg(), pcm::PCManager::coefficientToVectorMsg(), CONE_DISTANCE_TH, CONE_EPS_ANGLE_TH, CONE_MAX_ITERATION_LIMIT, CONE_MAX_OPENING_ANGLE_DEGREE, CONE_MAX_RADIUS_LIMIT, CONE_MIN_OPENING_ANGLE_DEGREE, CONE_MIN_RADIUS_LIMIT, CONE_NORMAL_DISTANCE_WEIGTH, getNormalizeAxesDirectionVector(), getPointOnAxes(), getVectorBetweenPoints(), pcm::PCManager::inlierToVectorMsg(), nh_ptr, pcm::PCManager::normForRosMsg(), srvm::PARAM_NAME_CONE_DISTANCE_TH, srvm::PARAM_NAME_CONE_EPS_ANGLE_TH, srvm::PARAM_NAME_CONE_MAX_ITERATION_LIMIT, srvm::PARAM_NAME_CONE_MAX_OPENING_ANGLE_DEGREE, srvm::PARAM_NAME_CONE_MAX_RADIUS_LIMIT, srvm::PARAM_NAME_CONE_MIN_OPENING_ANGLE_DEGREE, srvm::PARAM_NAME_CONE_MIN_RADIUS_LIMIT, srvm::PARAM_NAME_CONE_NORMAL_DISTANCE_WEIGHT, seg, pcm::PCManager::updateVisor(), vis, vis_mutex, VISUALIZE_RESULT, vector3d::x, vector3d::y, and vector3d::z.
Referenced by main().
void visSpin ()
Definition at line 46 of file cone_segmentation_srv.cpp.
References vis, and vis_mutex.
Referenced by main().
Variable Documentation
const double CONE_DISTANCE_TH = 0.0055 [static]
Definition at line 25 of file cone_segmentation_srv.cpp.
Referenced by ransacConeDetaction().
const double CONE_EPS_ANGLE_TH = 0.4 [static]
Definition at line 29 of file cone_segmentation_srv.cpp.
Referenced by ransacConeDetaction().
const int CONE_MAX_ITERATION_LIMIT = 1000 [static]
Definition at line 28 of file cone_segmentation_srv.cpp.
Referenced by ransacConeDetaction().
const double CONE_MAX_OPENING_ANGLE_DEGREE = 170.0 [static]
Definition at line 31 of file cone_segmentation_srv.cpp.
Referenced by ransacConeDetaction().
const double CONE_MAX_RADIUS_LIMIT = 0.500 [static]
Definition at line 27 of file cone_segmentation_srv.cpp.
Referenced by ransacConeDetaction().
const double CONE_MIN_OPENING_ANGLE_DEGREE = 10.0 [static]
Definition at line 30 of file cone_segmentation_srv.cpp.
Referenced by ransacConeDetaction().
const double CONE_MIN_RADIUS_LIMIT = 0.001 [static]
Definition at line 26 of file cone_segmentation_srv.cpp.
Referenced by ransacConeDetaction().
const double CONE_NORMAL_DISTANCE_WEIGTH = 0.0006 [static]
Definition at line 24 of file cone_segmentation_srv.cpp.
Referenced by ransacConeDetaction().
ros::NodeHandle* nh_ptr = NULL
Definition at line 21 of file cone_segmentation_srv.cpp.
Referenced by main(), and ransacConeDetaction().
boost::shared_ptr< visualization::PCLVisualizer> vis
Definition at line 42 of file cone_segmentation_srv.cpp.
Referenced by main(), ransacConeDetaction(), and visSpin().
boost::mutex vis_mutex
Definition at line 44 of file cone_segmentation_srv.cpp.
Referenced by ransacConeDetaction(), and visSpin().
boost::thread vis_thread
Definition at line 43 of file cone_segmentation_srv.cpp.
Referenced by main().
const bool VISUALIZE_RESULT = false
Definition at line 41 of file cone_segmentation_srv.cpp.
Referenced by main(), and ransacConeDetaction().