src/segmentation_services/cylinder_segmentation_srv.cpp File Reference
#include `ros/ros.h`
*
#include <pcl_ros/point_cloud.h>
*
#include <pcl/segmentation/sac_segmentation.h>
*
#include `pitt_msgs/PrimitiveSegmentation.h`
*
#include `../point_cloud_library/pc_manager.h`
*
#include `../point_cloud_library/srv_manager.h`
*
#include <boost/thread.hpp>
*
#include <boost/thread/mutex.hpp>
*
#include <boost/format.hpp>
*
Classes
struct vector3d
Functions
void visSpin ()
vector3d getNormalizeAxesDirectionVector (ModelCoefficients::Ptr coefficients)
vector3d getPointOnAxes (ModelCoefficients::Ptr coefficients, vector3d direction, float t)
vector3d getVectorBetweenPoints (vector3d p1, vector3d p2)
bool ransacCylinderDetaction (PrimitiveSegmentation::Request &req, PrimitiveSegmentation::Response &res)
int main (int argc, char **argv)
Variables
ros::NodeHandle * nh_ptr = NULL
static const double CYLINDER_NORMAL_DISTANCE_WEIGTH = 0.001
static const double CYLINDER_DISTANCE_TH = 0.008
static const double CYLINDER_MIN_RADIUS_LIMIT = 0.005
static const double CYLINDER_MAX_RADIUS_LIMIT = 0.500
static const int CYLINDER_MAX_ITERATION_LIMIT = 1000
static const double CYLINDER_EPS_ANGLE_TH = 0.0001
static const double CYLINDER_MIN_OPENING_ANGLE_DEGREE = 50.0
static const double CYLINDER_MAX_OPENING_ANGLE_DEGREE = 180.0
const bool VISUALIZE_RESULT = false
boost::shared_ptr
*
< visualization::PCLVisualizer > vis
boost::thread vis_thread
boost::mutex vis_mutex
Function Documentation
vector3d getNormalizeAxesDirectionVector (ModelCoefficients::Ptr coefficients)
Definition at line 53 of file cylinder_segmentation_srv.cpp.
References vector3d::x, vector3d::y, and vector3d::z.
Referenced by ransacCylinderDetaction().
vector3d getPointOnAxes (ModelCoefficients::Ptr coefficients, vector3d direction, float t)
Definition at line 64 of file cylinder_segmentation_srv.cpp.
References vector3d::x, vector3d::y, and vector3d::z.
Referenced by ransacCylinderDetaction().
vector3d getVectorBetweenPoints (vector3d p1, vector3d p2)
Definition at line 73 of file cylinder_segmentation_srv.cpp.
References vector3d::x, vector3d::y, and vector3d::z.
Referenced by ransacCylinderDetaction().
int main (int argc, char ** argv)
Definition at line 220 of file cylinder_segmentation_srv.cpp.
References pcm::PCManager::createVisor(), nh_ptr, ransacCylinderDetaction(), srvm::SRV_NAME_RANSAC_CYLINDER_FILTER, vis, vis_thread, visSpin(), and VISUALIZE_RESULT.
bool ransacCylinderDetaction (PrimitiveSegmentation::Request & req, PrimitiveSegmentation::Response & res)
Definition at line 82 of file cylinder_segmentation_srv.cpp.
References pcm::PCManager::cloudForRosMsg(), pcm::PCManager::coefficientToVectorMsg(), CYLINDER_DISTANCE_TH, CYLINDER_EPS_ANGLE_TH, CYLINDER_MAX_ITERATION_LIMIT, CYLINDER_MAX_OPENING_ANGLE_DEGREE, CYLINDER_MAX_RADIUS_LIMIT, CYLINDER_MIN_OPENING_ANGLE_DEGREE, CYLINDER_MIN_RADIUS_LIMIT, CYLINDER_NORMAL_DISTANCE_WEIGTH, getNormalizeAxesDirectionVector(), getPointOnAxes(), getVectorBetweenPoints(), pcm::PCManager::inlierToVectorMsg(), nh_ptr, pcm::PCManager::normForRosMsg(), srvm::PARAM_NAME_CYLINDER_DISTANCE_TH, srvm::PARAM_NAME_CYLINDER_EPS_ANGLE_TH, srvm::PARAM_NAME_CYLINDER_MAX_ITERATION_LIMIT, srvm::PARAM_NAME_CYLINDER_MAX_OPENING_ANGLE_DEGREE, srvm::PARAM_NAME_CYLINDER_MAX_RADIUS_LIMIT, srvm::PARAM_NAME_CYLINDER_MIN_OPENING_ANGLE_DEGREE, srvm::PARAM_NAME_CYLINDER_MIN_RADIUS_LIMIT, srvm::PARAM_NAME_CYLINDER_NORMAL_DISTANCE_WEIGHT, seg, pcm::PCManager::updateVisor(), vis, vis_mutex, VISUALIZE_RESULT, vector3d::x, vector3d::y, and vector3d::z.
Referenced by main().
void visSpin ()
Definition at line 45 of file cylinder_segmentation_srv.cpp.
References vis, and vis_mutex.
Referenced by main().
Variable Documentation
const double CYLINDER_DISTANCE_TH = 0.008 [static]
Definition at line 24 of file cylinder_segmentation_srv.cpp.
Referenced by ransacCylinderDetaction().
const double CYLINDER_EPS_ANGLE_TH = 0.0001 [static]
Definition at line 28 of file cylinder_segmentation_srv.cpp.
Referenced by ransacCylinderDetaction().
const int CYLINDER_MAX_ITERATION_LIMIT = 1000 [static]
Definition at line 27 of file cylinder_segmentation_srv.cpp.
Referenced by ransacCylinderDetaction().
const double CYLINDER_MAX_OPENING_ANGLE_DEGREE = 180.0 [static]
Definition at line 30 of file cylinder_segmentation_srv.cpp.
Referenced by ransacCylinderDetaction().
const double CYLINDER_MAX_RADIUS_LIMIT = 0.500 [static]
Definition at line 26 of file cylinder_segmentation_srv.cpp.
Referenced by ransacCylinderDetaction().
const double CYLINDER_MIN_OPENING_ANGLE_DEGREE = 50.0 [static]
Definition at line 29 of file cylinder_segmentation_srv.cpp.
Referenced by ransacCylinderDetaction().
const double CYLINDER_MIN_RADIUS_LIMIT = 0.005 [static]
Definition at line 25 of file cylinder_segmentation_srv.cpp.
Referenced by ransacCylinderDetaction().
const double CYLINDER_NORMAL_DISTANCE_WEIGTH = 0.001 [static]
Definition at line 23 of file cylinder_segmentation_srv.cpp.
Referenced by ransacCylinderDetaction().
ros::NodeHandle* nh_ptr = NULL
Definition at line 20 of file cylinder_segmentation_srv.cpp.
Referenced by main(), and ransacCylinderDetaction().
boost::shared_ptr< visualization::PCLVisualizer> vis
Definition at line 41 of file cylinder_segmentation_srv.cpp.
Referenced by main(), ransacCylinderDetaction(), and visSpin().
boost::mutex vis_mutex
Definition at line 43 of file cylinder_segmentation_srv.cpp.
Referenced by ransacCylinderDetaction(), and visSpin().
boost::thread vis_thread
Definition at line 42 of file cylinder_segmentation_srv.cpp.
Referenced by main().
const bool VISUALIZE_RESULT = false
Definition at line 40 of file cylinder_segmentation_srv.cpp.
Referenced by main(), and ransacCylinderDetaction().