src/segmentation_services/deep_filter_srv.cpp File Reference
#include `ros/ros.h`
*
#include <iostream>
*
#include `pitt_msgs/DeepFilter.h`
*
#include `../point_cloud_library/pc_manager.h`
*
#include `../point_cloud_library/srv_manager.h`
*
Functions
bool deepFiltering (DeepFilter::Request &req, DeepFilter::Response &res)
int main (int argc, char **argv)
Variables
const float DEFAULT_PARAM_DEEP_SRV_Z_THRESHOLD = 3.000f
Function Documentation
bool deepFiltering (DeepFilter::Request & req, DeepFilter::Response & res)
Definition at line 27 of file deep_filter_srv.cpp.
References DEFAULT_PARAM_DEEP_SRV_Z_THRESHOLD, and srvm::getServiceFloatParameter().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 59 of file deep_filter_srv.cpp.
References deepFiltering(), and srvm::SRV_NAME_DEEP_FILTER.
Variable Documentation
const float DEFAULT_PARAM_DEEP_SRV_Z_THRESHOLD = 3.000f
Definition at line 20 of file deep_filter_srv.cpp.
Referenced by deepFiltering().