src/obj_segmentation.cpp File Reference
The PITT starting node, to preprocessing the Point Cloud for primitive identification.
#include <pcl_ros/point_cloud.h>
*
#include <pcl/common/transforms.h>
*
#include <tf/transform_listener.h>
*
#include <std_msgs/Float64.h>
*
#include `pitt_msgs/DeepFilter.h`
*
#include `pitt_msgs/SupportSegmentation.h`
*
#include `pitt_msgs/ClusterSegmentation.h`
*
#include `pitt_msgs/ArmFilter.h`
*
#include `pitt_msgs/ClustersOutput.h`
*
#include `point_cloud_library/pc_manager.h`
*
#include `point_cloud_library/srv_manager.h`
*
Typedefs
typedef vector
*
< pitt_msgs::Support > InlierSupports
a vector of costom messages to describe tables.
typedef boost::shared_ptr
*
< vector< pitt_msgs::Support > > InlierSupportsPtr
a pointer to a InlierSupports.
typedef vector
*
< pitt_msgs::InliersCluster > InlierClusters
a vector of costom messages to describe objects on a table.
typedef boost::shared_ptr
*
< vector
*
< pitt_msgs::InliersCluster > > InlierClusterPtr
a pointer to a InlierClusters.
Functions
void visSpin ()
make the visualisation spinning without lagging acroos multi updating.
bool callDeepFilter (PCLCloudPtr &cloud)
call deep_filter_srv.cpp ROS service.
bool callArmFilter (PCLCloudPtr &cloud)
call arm_filter_srv.cpp ROS service.
InlierSupportsPtr callSupportFilter (PCLCloudPtr inputCloud, PCLNormalPtr normal)
call support_segmentation_srv.cpp ROS service.
InlierClusterPtr callClusterSegmentation (PCLCloudPtr cloud)
call cluster_segmentation_srv.cpp ROS service.
void depthAcquisition (const PointCloud2Ptr &input)
Node callback.
int main (int argc, char **argv)
It initialise this ROS node and spin in order to activate the depthAcquisition callback as soon as new data is available. It also listens and updates the pclTransform matrix.
Variables
static const int MIN_POINT_IN_ORIGINAL_CLOUD = 30
the cloud will be not not processed if has less number of points
bool inputShowOriginalCloud
flag for showing raw cloud (white points) on the visualiser of this node.
bool inputShowSupportClouds
flag for showing identified tables (brown points) on the visualiser of this node.
bool inputShowClusterClouds
flag for showing identified objects (random colors) on the visualiser of this node.
bool inputShowObjectOnSupport
flag for showing identified all the points on the table (orange points) on the visualiser of this node.
string centroidLogFilePath
file path to lag the centroids of the acquired objects in a table. Set to empty to do not log on file.
pcm::PCManager * manager = new pcm::PCManager(false)
variable to initialise the pcm::PCManager.
ros::NodeHandle * nh_ptr = NULL
ros handle passed across all services calls.
boost::shared_ptr
*
< visualization::PCLVisualizer > vis
the PCL visualiser for this node.
ros::Publisher clusterPub
the ROS publisher in which the message of a new acquistion will be send.
Eigen::Matrix4f pclTransform
the transformation matrix between the RGB-D sensor and the srvm::PARAM_NAME_INPUT_CLOUD_REFERENCE_FRAME frame (it can be changed on the fly).
boost::thread vis_thread
for a better visualiser updating on parallel thread.
boost::mutex vis_mutex
for a better visualiser updating during different services calls.
string log_str_depth = `Loading...`
string that will contains info about deep_filter_srv.cpp service, shown in the visualiser while the parameters are changed on the fly.
string log_str_supp = `Loading...`
string that will contains info about support_segmentation_srv.cpp service, shown in the visualiser while the parameters are changed on the fly.
long scanId = 0
so far, it is used only for logging.
Detailed Description
The PITT starting node, to preprocessing the Point Cloud for primitive identification. File
           src/obj_segmentation.cpp
Author
Buoncompagni Luca,
Contacts
           luca.buoncompagni@edu.unige.it
Date
May 10, 2015
Institution
           DIBRIS, emaroLAB, University of Genoa.
Version
2.1
 Programm behaviour
          This file implements a ROS node that acquires Kinect Point Cloud (PC) from the topic specified through the: srvm::DEFAULT_INPUT_PARAM_RAW_CLOUD_TOPIC parameter (see main function for more) and performs preprocessing (on depthAcquisition callback) with the following order:
PC downsampling (see PCL documentation for more),
filtering out far points (see deep_filter_srv.cpp ROS service),
filtering out points of robotic arms (see arm_filter_srv.cpp ROS service),
PC transforming w.r.t. robot base frame (see TF for more),
tables segmentation (see supports_segmentation_srv.cpp ROS service),
objects segmentation, for each support (see cluster_segmentation_srv.cpp ROS service)
          The results of this computation (for each table) is published into the topic specified through the srvm::TOPIC_OUT_NAME_OBJECT_PERCEPTION parameter. This topic accommodates an array of
pitt_msgs/msg/InlierCluster.msg
 messages (see pitt_msgs package for more details) that contains, for each recognised object in that table:
sensor_msgs/PointCloud2 cloud: the cloud containing only the object,
int32[] inliers: the index of the points of the object w.r.t. the original cloud,
float32 x_centroid, y_centroid, z_centroid: the coordinates of the center of mass of the cloud
int32 shape_id: object identifier. At this stage of the architecture this value is not set (the tracker will do it, see the pitt_geometric_tracking for an example).
See Also
pc_manager.h
pc_primitive.h
srv_manager.h
ransac_segmentation.cpp
<a href="https://github.com/EmaroLab/pitt_geometric_tracking>pitt_geometric_tracking
Definition in file obj_segmentation.cpp.
Typedef Documentation
typedef boost::shared_ptr< vector< pitt_msgs::InliersCluster> > InlierClusterPtr
a pointer to a InlierClusters.
See Also
pitt_msgs/msg/InliersCluster.msg
Definition at line 92 of file obj_segmentation.cpp.
typedef vector< pitt_msgs::InliersCluster> InlierClusters
a vector of costom messages to describe objects on a table.
See Also
pitt_msgs/msg/InliersCluster.msg
Definition at line 87 of file obj_segmentation.cpp.
typedef vector< pitt_msgs::Support> InlierSupports
a vector of costom messages to describe tables.
See Also
pitt_msgs/msg/Support.msg
Definition at line 77 of file obj_segmentation.cpp.
typedef boost::shared_ptr< vector< pitt_msgs::Support> > InlierSupportsPtr
a pointer to a InlierSupports.
See Also
pitt_msgs/msg/Support.msg
Definition at line 82 of file obj_segmentation.cpp.
Function Documentation
bool callArmFilter (PCLCloudPtr & cloud)
call arm_filter_srv.cpp ROS service.
It removes, from input parameter, all the points that are belonging to a bounding box around the robot arms.
Parameters
cloud the PC from which remove all the points of the arms.
Returns
false if an error occurs during service call, true otherwise.
Following, the steeps that this function performs:
load the baunding box parameters (default values: srvm::DEFAULT_SERVICE_VEC_PARAMETER_REQUEST):
srvm::PARAM_NAME_ARM_SRV_MIN_FOREARM_BOX,
srvm::PARAM_NAME_ARM_SRV_MAX_FOREARM_BOX,
srvm::PARAM_NAME_ARM_SRV_MIN_ELBOW_BOX,
srvm::PARAM_NAME_ARM_SRV_MAX_ELBOW_BOX,
initialise arm filter server,
set input data and parameters,
call service
check for error during service calls.
get the repose and overwrite the cloud, if no errors occur.
Definition at line 251 of file obj_segmentation.cpp.
References pcm::PCManager::cloudForRosMsg(), pcm::PCManager::cloudToRosMsg(), srvm::DEFAULT_SERVICE_VEC_PARAMETER_REQUEST(), nh_ptr, srvm::PARAM_NAME_ARM_SRV_MAX_ELBOW_BOX, srvm::PARAM_NAME_ARM_SRV_MAX_FOREARM_BOX, srvm::PARAM_NAME_ARM_SRV_MIN_ELBOW_BOX, srvm::PARAM_NAME_ARM_SRV_MIN_FOREARM_BOX, and srvm::SRV_NAME_ARM_FILTER.
Referenced by depthAcquisition().
InlierClusterPtr callClusterSegmentation (PCLCloudPtr cloud)
call cluster_segmentation_srv.cpp ROS service.
It segments a PC in smaller structure where each of them represents a separated object. The points are also described in terms of index in the original cloud.
Parameters
cloud the PC to be segmented in clusters.
Returns
an array of structures that describes separated objects in the cloud. An empty array if errors occur on service call.
Following, the steeps that this function performs:
load the parameters for the server (default values: srvm::DEFAULT_SERVICE_PARAMETER_REQUEST or srvm::DEFAULT_SERVICE_PARAMETER_REQUEST_F):
srvm::PARAM_NAME_CLUSTER_TOLERANCE,
srvm::PARAM_NAME_CLUSTER_MIN_RATE,
srvm::PARAM_NAME_CLUSTER_MAX_RATE,
srvm::PARAM_NAME_CLUSTER_TOLERANCE,
initialise claster segmentation server,
set input data and parameters,
call service,
check and log for errors,
get the service responce to be returned.
Definition at line 387 of file obj_segmentation.cpp.
References pcm::PCManager::cloudToRosMsg(), srvm::DEFAULT_SERVICE_PARAMETER_REQUEST, srvm::DEFAULT_SERVICE_PARAMETER_REQUEST_F, nh_ptr, srvm::PARAM_NAME_CLUSTER_MAX_RATE, srvm::PARAM_NAME_CLUSTER_MIN_RATE, srvm::PARAM_NAME_CLUSTER_TOLERANCE, and srvm::SRV_NAME_CUSTER_FILTER.
Referenced by depthAcquisition().
bool callDeepFilter (PCLCloudPtr & cloud)
call deep_filter_srv.cpp ROS service.
It removes, from input parameter, all the points further than a threshold on the z-axis of the cloud.
Parameters
cloud the PC from which remove all the points further than a threshold.
Returns
false if an error occurs during service call, true otherwise.
Following, the steeps that this function performs:
load the threshold parameter: srvm::PARAM_NAME_DEEP_SRV_Z_THRESHOLD from ROS pull. Use srvm::DEFAULT_SERVICE_PARAMETER_REQUEST_F as default value,
update visualiser texts about the deep threshold value,
initialise deep filter server,
set input data and parameters,
call service,
check for error during service calls.
get the repose and overwrite the cloud, if no errors occur.
Definition at line 207 of file obj_segmentation.cpp.
References pcm::PCManager::cloudForRosMsg(), pcm::PCManager::cloudToRosMsg(), srvm::DEFAULT_SERVICE_PARAMETER_REQUEST_F, inputShowClusterClouds, inputShowObjectOnSupport, inputShowOriginalCloud, inputShowSupportClouds, log_str_depth, nh_ptr, srvm::PARAM_NAME_DEEP_SRV_Z_THRESHOLD, srvm::SRV_NAME_DEEP_FILTER, vis, and vis_mutex.
Referenced by depthAcquisition().
InlierSupportsPtr callSupportFilter (PCLCloudPtr inputCloud, PCLNormalPtr normal)
call support_segmentation_srv.cpp ROS service.
It detects all the vertical planes in the scene and returns the index of their point w.r.t. to original cloud.
Parameters
inputCloud the PC from which retrieve the supports.
normal the Nolrmal vector of the points of the above cloud.
Returns
a vector of set of index indicating the points of a support w.r.t. to acquired cloud. It returns an empty array if errors occur during service call.
Following, the steeps that this function performs:
load the parameters for the server (default values: srvm::DEFAULT_SERVICE_PARAMETER_REQUEST or srvm::DEFAULT_SERVICE_PARAMETER_REQUEST_F):
srvm::PARAM_NAME_MIN_ITERATIVE_CLOUD_PERCENTAGE,
srvm::PARAM_NAME_MIN_ITERATIVE_SUPPORT_PERCENTAGE,
srvm::PARAM_NAME_HORIZONTAL_VARIANCE_THRESHOLD,
srvm::PARAM_NAME_RANSAC_IN_SHAPE_DISTANCE_POINT_THRESHOLD,
srvm::PARAM_NAME_RANSAC_MODEL_NORMAL_DISTANCE_WEIGHT,
srvm::PARAM_NAME_RANSAC_MAX_ITERATION_THRESHOLD,
srvm::PARAM_NAME_HORIZONTAL_AXIS,
srvm::PARAM_NAME_SUPPORT_EDGE_REMOVE_OFFSET,
initialise support segmentation server,
set input data and parameters,
call service,
check and log for errors,
get the service responce to be returned,
update the visualiser texts.
Definition at line 299 of file obj_segmentation.cpp.
References pcm::PCManager::cloudToRosMsg(), srvm::DEFAULT_SERVICE_PARAMETER_REQUEST, srvm::DEFAULT_SERVICE_PARAMETER_REQUEST_F, srvm::DEFAULT_SERVICE_VEC_PARAMETER_REQUEST(), horizontalAxis, inputShowClusterClouds, inputShowObjectOnSupport, inputShowOriginalCloud, inputShowSupportClouds, log_str_supp, nh_ptr, pcm::PCManager::normToRosMsg(), srvm::PARAM_NAME_HORIZONTAL_AXIS, srvm::PARAM_NAME_HORIZONTAL_VARIANCE_THRESHOLD, srvm::PARAM_NAME_MIN_ITERATIVE_CLOUD_PERCENTAGE, srvm::PARAM_NAME_MIN_ITERATIVE_SUPPORT_PERCENTAGE, srvm::PARAM_NAME_RANSAC_IN_SHAPE_DISTANCE_POINT_THRESHOLD, srvm::PARAM_NAME_RANSAC_MAX_ITERATION_THRESHOLD, srvm::PARAM_NAME_RANSAC_MODEL_NORMAL_DISTANCE_WEIGHT, srvm::PARAM_NAME_SUPPORT_EDGE_REMOVE_OFFSET, ransacMaxIteration, srvm::SRV_NAME_SUPPORT_FILTER, vis, and vis_mutex.
Referenced by depthAcquisition().
void depthAcquisition (const PointCloud2Ptr & input)
Node callback.
It is called as soon as a new PC acquisition is available from the sensor. It processes the clud based on ROS services:
deep_filter_srv.cpp
arm_filter_srv.cpp
supports_segmentation_srv.cpp
cluster_segmentation_srv.cpp
and publishes the output message if a successfully acquisition occurs.
Parameters
input the Point Cloud message published on the input topic.
See Also
main
callDeepFilter
callArmFilter
callSupportFilter
callClusterSegmentation
Following, the steeps that this function performs:
get Kinect PC inputs as a standard pcl cloud,
compute down-sampling (pcm::PCManager::downSampling),
call deep filter server (callDeepFilter),
if success: call arm filter server (callArmFilter),
if success: transform the cloud w.r.t. pclTransform,
stop if too few points are remaining (w.r.t. MIN_POINT_IN_ORIGINAL_CLOUD). Otherwise ...
compute the normals off all the points,
show original cloud as gray points, if inputShowOriginalCloud is true,
call the support segmentation service (callSupportFilter),
for all the detected supports ...
show supports as brown points, if inputShowSupportClouds is true,
show cloud of the object on the horizontal plane, as orange points, if inputShowObjectOnSupport is true,
call cluster segmentation service (callClusterSegmentation),
if there is at least one cluster, prepare node output message containing all the claster information for a support,
show cloud of the segmented objects, with random colors, if inputShowClusterClouds is true,
prepare detached clusters center of mass for logging,
publish the center of mass of the detached clusters for a specific support,
print on screen the results,
if centroidLogFilePath is not empty, print the same results on file.
Definition at line 451 of file obj_segmentation.cpp.
References callArmFilter(), callClusterSegmentation(), callDeepFilter(), callSupportFilter(), centroidFileLog, centroidLogFilePath, pcm::PCManager::cloudForRosMsg(), clusterPub, pcm::PCManager::downSampling(), pcm::PCManager::estimateNormal(), inputShowClusterClouds, inputShowObjectOnSupport, inputShowOriginalCloud, inputShowSupportClouds, MIN_POINT_IN_ORIGINAL_CLOUD, pclTransform, scanId, pcm::PCManager::updateVisor(), vis, vis_mutex, and pcm::PCManager::writeToFile().
Referenced by main().
int main (int argc, char ** argv)
It initialise this ROS node and spin in order to activate the depthAcquisition callback as soon as new data is available. It also listens and updates the pclTransform matrix.
Parameters
argv the value of the input parameters, respectively:
the name of the input topic (containing a PointCloud2) (default value: srvm::DEFAULT_INPUT_PARAM_RAW_CLOUD_TOPIC),
the flag for showing the original cloud (see inputShowOriginalCloud),
the flag for showing the supports cloud (see inputShowSupportClouds),
the flag for showing the clusters cloud (see inputShowClusterClouds),
the flag for showing the cloud of the object above the supports (see inputShowObjectOnSupport),
the file path in which store the logging information about the segmented cluster centroids (see centroidLogFilePath).
argc the number of input parameters + 1 (defaults: executable name). It has to be equal to 7.
Returns
0.
Following, the steeps that this function performs:
instantiate the ROS node with name `obj_segmentation`,
read and configure input parameters,
log info about this node set up,
set subscriber to get RGB-D data (from the topic defied by argv[ 1]) that will be processed from depthAcquisition callback,
eventually, create window (with name `Object Table Segmentation`) to visualize clouds from this node,
set the publisher for the node output to contains
pitt_msgs::msg::ClustersOutput
 and named as srvm::TOPIC_OUT_NAME_OBJECT_PERCEPTION (with buffer size 10),
wait for callbacl and listen for the transformation between the sensor camera (specified through the parameter: srvm::PARAM_NAME_INPUT_CLOUD_REFERENCE_FRAME) and the output frame (specified through the parameter: srvm::PARAM_NAME_OUTPUT_CLOUD_REFERENCE_FRAME)..
Definition at line 571 of file obj_segmentation.cpp.
References centroidLogFilePath, clusterPub, pcm::PCManager::createVisor(), srvm::DEFAULT_INPUT_PARAM_CENTROID_LOG_FILE, srvm::DEFAULT_INPUT_PARAM_RAW_CLOUD_TOPIC, srvm::DEFAULT_INPUT_PARAM_SHOW_CLUSTERS, srvm::DEFAULT_INPUT_PARAM_SHOW_OBJECT_ON_SUPPORT, srvm::DEFAULT_INPUT_PARAM_SHOW_ORIGINAL_CLOUD, srvm::DEFAULT_INPUT_PARAM_SHOW_SUPPORTS, srvm::DEFAULT_PARAM_INPUT_CLOUD_REFERENCE_FRAME, srvm::DEFAULT_PARAM_OUTPUT_CLOUD_REFERENCE_FRAME, srvm::DEFAULT_TF_WAIT_SECONDS, depthAcquisition(), srvm::getBoolPtrParameter(), srvm::getFlagValueToPrint(), srvm::getPathPtrParameter(), srvm::getStringParameter(), srvm::getStringPtrParameter(), inputShowClusterClouds, inputShowObjectOnSupport, inputShowOriginalCloud, inputShowSupportClouds, log_str_depth, log_str_supp, nh_ptr, srvm::PARAM_NAME_INPUT_CLOUD_REFERENCE_FRAME, srvm::PARAM_NAME_OUTPUT_CLOUD_REFERENCE_FRAME, pclTransform, srvm::TOPIC_OUT_NAME_OBJECT_PERCEPTION, vis, vis_thread, visSpin(), and pcm::PCManager::writeToFile().
void visSpin ()
make the visualisation spinning without lagging acroos multi updating.
Definition at line 192 of file obj_segmentation.cpp.
References vis, and vis_mutex.
Referenced by main().
Variable Documentation
string centroidLogFilePath
file path to lag the centroids of the acquired objects in a table. Set to empty to do not log on file.
The data, that will be appended on the file for each acquisition will have the following shape:
"scan id, support idx, cluster idx, centroid X, centroid Y, centroid Z;\n"
This is a global input parameter that is settable from launcher and acquired during node initialization (see also main function: argv[ 6]).
 It cannot be changed on the fly.
 It default values is set to: srvm::DEFAULT_INPUT_PARAM_CENTROID_LOG_FILE
Definition at line 156 of file obj_segmentation.cpp.
Referenced by depthAcquisition(), and main().
ros::Publisher clusterPub
the ROS publisher in which the message of a new acquistion will be send.
Its name is: srvm::TOPIC_OUT_NAME_OBJECT_PERCEPTION.
Definition at line 171 of file obj_segmentation.cpp.
Referenced by depthAcquisition(), and main().
bool inputShowClusterClouds
flag for showing identified objects (random colors) on the visualiser of this node.
This is a global input parameter that is settable from launcher and acquired during node initialization (see also main function: argv[ 4]).
 It cannot be changed on the fly.
 It default values is set to: srvm::DEFAULT_INPUT_PARAM_SHOW_CLUSTERS
Definition at line 135 of file obj_segmentation.cpp.
Referenced by callDeepFilter(), callSupportFilter(), depthAcquisition(), and main().
bool inputShowObjectOnSupport
flag for showing identified all the points on the table (orange points) on the visualiser of this node.
This is a global input parameter that is settable from launcher and acquired during node initialization (see also main function: argv[ 5]).
 It cannot be changed on the fly.
 It default values is set to: srvm::DEFAULT_INPUT_PARAM_SHOW_OBJECT_ON_SUPPORT
Definition at line 144 of file obj_segmentation.cpp.
Referenced by callDeepFilter(), callSupportFilter(), depthAcquisition(), and main().
bool inputShowOriginalCloud
flag for showing raw cloud (white points) on the visualiser of this node.
This is a global input parameter that is settable from launcher and acquired during node initialization (see also main function: argv[ 2]).
 It cannot be changed on the fly.
 It default values is set to: srvm::DEFAULT_INPUT_PARAM_SHOW_ORIGINAL_CLOUD
Definition at line 117 of file obj_segmentation.cpp.
Referenced by callDeepFilter(), callSupportFilter(), depthAcquisition(), and main().
bool inputShowSupportClouds
flag for showing identified tables (brown points) on the visualiser of this node.
This is a global input parameter that is settable from launcher and acquired during node initialization (see also main function: argv[ 3]).
 It cannot be changed on the fly.
 It default values is set to: srvm::DEFAULT_INPUT_PARAM_SHOW_SUPPORTS
Definition at line 126 of file obj_segmentation.cpp.
Referenced by callDeepFilter(), callSupportFilter(), depthAcquisition(), and main().
string log_str_depth = `Loading...`
string that will contains info about deep_filter_srv.cpp service, shown in the visualiser while the parameters are changed on the fly.
Definition at line 179 of file obj_segmentation.cpp.
Referenced by callDeepFilter(), and main().
string log_str_supp = `Loading...`
string that will contains info about support_segmentation_srv.cpp service, shown in the visualiser while the parameters are changed on the fly.
Definition at line 181 of file obj_segmentation.cpp.
Referenced by callSupportFilter(), and main().
pcm::PCManager* manager = new pcm::PCManager(false)
variable to initialise the pcm::PCManager.
Definition at line 165 of file obj_segmentation.cpp.
const int MIN_POINT_IN_ORIGINAL_CLOUD = 30 [static]
the cloud will be not not processed if has less number of points
Definition at line 101 of file obj_segmentation.cpp.
Referenced by depthAcquisition().
ros::NodeHandle* nh_ptr = NULL
ros handle passed across all services calls.
Definition at line 167 of file obj_segmentation.cpp.
Referenced by callArmFilter(), callClusterSegmentation(), callDeepFilter(), callSupportFilter(), and main().
Eigen::Matrix4f pclTransform
the transformation matrix between the RGB-D sensor and the srvm::PARAM_NAME_INPUT_CLOUD_REFERENCE_FRAME frame (it can be changed on the fly).
Definition at line 173 of file obj_segmentation.cpp.
Referenced by depthAcquisition(), and main().
long scanId = 0
so far, it is used only for logging.
Definition at line 183 of file obj_segmentation.cpp.
Referenced by depthAcquisition().
boost::shared_ptr< visualization::PCLVisualizer> vis
the PCL visualiser for this node.
It will happear if at least one of: inputShowOriginalCloud, inputShowSupportClouds, inputShowClusterClouds, inputShowObjectOnSupport; is true.
Definition at line 169 of file obj_segmentation.cpp.
Referenced by callDeepFilter(), callSupportFilter(), depthAcquisition(), main(), and visSpin().
boost::mutex vis_mutex
for a better visualiser updating during different services calls.
Definition at line 177 of file obj_segmentation.cpp.
Referenced by callDeepFilter(), callSupportFilter(), depthAcquisition(), and visSpin().
boost::thread vis_thread
for a better visualiser updating on parallel thread.
Definition at line 175 of file obj_segmentation.cpp.
Referenced by main().