src/segmentation_services/plane_segmentation_srv.cpp File Reference
#include `ros/ros.h`
*
#include <pcl_ros/point_cloud.h>
*
#include <pcl/segmentation/sac_segmentation.h>
*
#include `pitt_msgs/PrimitiveSegmentation.h`
*
#include `../point_cloud_library/pc_manager.h`
*
#include `../point_cloud_library/srv_manager.h`
*
Functions
bool ransacPlaneDetaction (PrimitiveSegmentation::Request &req, PrimitiveSegmentation::Response &res)
int main (int argc, char **argv)
Variables
ros::NodeHandle * nh_ptr = NULL
static const double PLANE_NORMAL_DISTANCE_WEIGTH = 0.001
static const double PLANE_DISTANCE_TH = 0.007
static const int PLANE_MAX_ITERATION_LIMIT = 1000
static const double PLANE_EPS_ANGLE_TH = 0.0
static const double PLANE_MIN_OPENING_ANGLE_DEGREE = 0.0
static const double PLANE_MAX_OPENING_ANGLE_DEGREE = 10.0
Function Documentation
int main (int argc, char ** argv)
Definition at line 78 of file plane_segmentation_srv.cpp.
References nh_ptr, ransacPlaneDetaction(), and srvm::SRV_NAME_RANSAC_PLANE_FILTER.
bool ransacPlaneDetaction (PrimitiveSegmentation::Request & req, PrimitiveSegmentation::Response & res)
Definition at line 27 of file plane_segmentation_srv.cpp.
References pcm::PCManager::cloudForRosMsg(), pcm::PCManager::coefficientToVectorMsg(), pcm::PCManager::inlierToVectorMsg(), nh_ptr, pcm::PCManager::normForRosMsg(), srvm::PARAM_NAME_PLANE_DISTANCE_TH, srvm::PARAM_NAME_PLANE_EPS_ANGLE_TH, srvm::PARAM_NAME_PLANE_MAX_ITERATION_LIMIT, srvm::PARAM_NAME_PLANE_MAX_OPENING_ANGLE_DEGREE, srvm::PARAM_NAME_PLANE_MIN_OPENING_ANGLE_DEGREE, srvm::PARAM_NAME_PLANE_NORMAL_DISTANCE_WEIGHT, PLANE_DISTANCE_TH, PLANE_EPS_ANGLE_TH, PLANE_MAX_ITERATION_LIMIT, PLANE_MAX_OPENING_ANGLE_DEGREE, PLANE_MIN_OPENING_ANGLE_DEGREE, PLANE_NORMAL_DISTANCE_WEIGTH, and seg.
Referenced by main().
Variable Documentation
ros::NodeHandle* nh_ptr = NULL
Definition at line 16 of file plane_segmentation_srv.cpp.
Referenced by main(), and ransacPlaneDetaction().
const double PLANE_DISTANCE_TH = 0.007 [static]
Definition at line 20 of file plane_segmentation_srv.cpp.
Referenced by ransacPlaneDetaction().
const double PLANE_EPS_ANGLE_TH = 0.0 [static]
Definition at line 22 of file plane_segmentation_srv.cpp.
Referenced by ransacPlaneDetaction().
const int PLANE_MAX_ITERATION_LIMIT = 1000 [static]
Definition at line 21 of file plane_segmentation_srv.cpp.
Referenced by ransacPlaneDetaction().
const double PLANE_MAX_OPENING_ANGLE_DEGREE = 10.0 [static]
Definition at line 24 of file plane_segmentation_srv.cpp.
Referenced by ransacPlaneDetaction().
const double PLANE_MIN_OPENING_ANGLE_DEGREE = 0.0 [static]
Definition at line 23 of file plane_segmentation_srv.cpp.
Referenced by ransacPlaneDetaction().
const double PLANE_NORMAL_DISTANCE_WEIGTH = 0.001 [static]
Definition at line 19 of file plane_segmentation_srv.cpp.
Referenced by ransacPlaneDetaction().