src/segmentation_services/sphere_segmentation_srv.cpp File Reference
#include `ros/ros.h`
*
#include <pcl_ros/point_cloud.h>
*
#include <pcl/segmentation/sac_segmentation.h>
*
#include `pitt_msgs/PrimitiveSegmentation.h`
*
#include `../point_cloud_library/pc_manager.h`
*
#include `../point_cloud_library/srv_manager.h`
*
Functions
bool ransacSphereDetection (PrimitiveSegmentation::Request &req, PrimitiveSegmentation::Response &res)
int main (int argc, char **argv)
Variables
ros::NodeHandle * nh_ptr = NULL
static const double SPHERE_NORMAL_DISTANCE_WEIGTH = 0.001
static const double SPHERE_DISTANCE_TH = 0.007
static const double SPHERE_MIN_RADIUS_LIMIT = 0.005
static const double SPHERE_MAX_RADIUS_LIMIT = 0.500
static const int SPHERE_MAX_ITERATION_LIMIT = 1000
static const double SPHERE_EPS_ANGLE_TH = 0.0
static const double SPHERE_MIN_OPENING_ANGLE_DEGREE = 100.0
static const double SPHERE_MAX_OPENING_ANGLE_DEGREE = 180.0
Function Documentation
int main (int argc, char ** argv)
Definition at line 100 of file sphere_segmentation_srv.cpp.
References nh_ptr, ransacSphereDetection(), and srvm::SRV_NAME_RANSAC_SPHERE_FILTER.
bool ransacSphereDetection (PrimitiveSegmentation::Request & req, PrimitiveSegmentation::Response & res)
Definition at line 29 of file sphere_segmentation_srv.cpp.
References pcm::PCManager::cloudForRosMsg(), pcm::PCManager::coefficientToVectorMsg(), pcm::PCManager::inlierToVectorMsg(), nh_ptr, pcm::PCManager::normForRosMsg(), srvm::PARAM_NAME_SPHERE_DISTANCE_TH, srvm::PARAM_NAME_SPHERE_EPS_ANGLE_TH, srvm::PARAM_NAME_SPHERE_MAX_ITERATION_LIMIT, srvm::PARAM_NAME_SPHERE_MAX_OPENING_ANGLE_DEGREE, srvm::PARAM_NAME_SPHERE_MAX_RADIUS_LIMIT, srvm::PARAM_NAME_SPHERE_MIN_OPENING_ANGLE_DEGREE, srvm::PARAM_NAME_SPHERE_MIN_RADIUS_LIMIT, srvm::PARAM_NAME_SPHERE_NORMAL_DISTANCE_WEIGHT, seg, SPHERE_DISTANCE_TH, SPHERE_EPS_ANGLE_TH, SPHERE_MAX_ITERATION_LIMIT, SPHERE_MAX_OPENING_ANGLE_DEGREE, SPHERE_MAX_RADIUS_LIMIT, SPHERE_MIN_OPENING_ANGLE_DEGREE, SPHERE_MIN_RADIUS_LIMIT, and SPHERE_NORMAL_DISTANCE_WEIGTH.
Referenced by main().
Variable Documentation
ros::NodeHandle* nh_ptr = NULL
Definition at line 16 of file sphere_segmentation_srv.cpp.
Referenced by main(), and ransacSphereDetection().
const double SPHERE_DISTANCE_TH = 0.007 [static]
Definition at line 20 of file sphere_segmentation_srv.cpp.
Referenced by ransacSphereDetection().
const double SPHERE_EPS_ANGLE_TH = 0.0 [static]
Definition at line 24 of file sphere_segmentation_srv.cpp.
Referenced by ransacSphereDetection().
const int SPHERE_MAX_ITERATION_LIMIT = 1000 [static]
Definition at line 23 of file sphere_segmentation_srv.cpp.
Referenced by ransacSphereDetection().
const double SPHERE_MAX_OPENING_ANGLE_DEGREE = 180.0 [static]
Definition at line 26 of file sphere_segmentation_srv.cpp.
Referenced by ransacSphereDetection().
const double SPHERE_MAX_RADIUS_LIMIT = 0.500 [static]
Definition at line 22 of file sphere_segmentation_srv.cpp.
Referenced by ransacSphereDetection().
const double SPHERE_MIN_OPENING_ANGLE_DEGREE = 100.0 [static]
Definition at line 25 of file sphere_segmentation_srv.cpp.
Referenced by ransacSphereDetection().
const double SPHERE_MIN_RADIUS_LIMIT = 0.005 [static]
Definition at line 21 of file sphere_segmentation_srv.cpp.
Referenced by ransacSphereDetection().
const double SPHERE_NORMAL_DISTANCE_WEIGTH = 0.001 [static]
Definition at line 19 of file sphere_segmentation_srv.cpp.
Referenced by ransacSphereDetection().