src/segmentation_services/supports_segmentation_srv.cpp File Reference
#include `ros/ros.h`
*
#include <iostream>
*
#include `math.h`
*
#include <pcl_ros/point_cloud.h>
*
#include <std_msgs/String.h>
*
#include <pcl/segmentation/sac_segmentation.h>
*
#include <pcl/filters/extract_indices.h>
*
#include `pitt_msgs/SupportSegmentation.h`
*
#include `pitt_msgs/Support.h`
*
#include `../point_cloud_library/pc_manager.h`
*
#include `../point_cloud_library/srv_manager.h`
*
#include <boost/thread.hpp>
*
#include <boost/thread/mutex.hpp>
*
Functions
void initializeInputParameters (SupportSegmentation::Request &req)
void ransacPlaneSegmentator (PCLCloudPtr inputCloud, PCLNormalPtr normals, PointIndices::Ptr &inlierOutput, ModelCoefficients::Ptr &coefficientOutput)
ExtractIndices< PointXYZ > extract (true)
void removePlaneInliner (PCLCloudPtr inputCloud, PointIndices::Ptr &removeIndex, PCLCloudPtr output)
bool valueBelongsToArray (int value, PointIndices::Ptr inliers)
PrimitiveIdxPtr createNewIdxMap (PrimitiveIdxPtr previousInliersMap, PointIndices::Ptr inliers, int level)
bool isHorizontalPlane (PCLNormalPtr normal, ModelCoefficients::Ptr coefficients, vector< float > referimentAxis)
PCLCloudPtr getPointOnPlane (PCLCloudPtr plane, PrimitiveIdxPtr inlierIdx, int mapLevel)
bool findSupports (SupportSegmentation::Request &req, SupportSegmentation::Response &res)
int main (int argc, char **argv)
Variables
const float DEFAULT_PARAM_SUPPORT_SRV_MIN_ITERATIVE_CLOUD_PERCENTAGE = 0.030f
const float DEFAULT_PARAM_SUPPORT_SRV_MIN_ITERATIVE_SUPPORT_PERCENTAGE = 0.030f
const float DEFAULT_PARAM_SUPPORT_SRV_VARIANCE_THRESHOLD_FOR_HORIZONTAL = 0.09f
const float DEFAULT_PARAM_SUPPORT_SRV_RANSAC_DISTANCE_POINT_IN_SHAPE_THRESHOLD = 0.02f
const float DEFAULT_PARAM_SUPPORT_SRV_RANSAC_MODEL_NORMAL_DISTANCE_WEIGHT = 0.9f
const int DEFAULT_PARAM_SUPPORT_SRV_RANSAC_MAX_ITERATION_THRESHOLD = 10
const float DEFAULT_PARAM_SUPPORT_SRV_HORIZONTAL_AXIS [3] = { 0.0f, 0.0f, -1.0f}
const float DEFAULT_PARAM_SUPPORT_SRV_SUPPORT_EDGE_REMOVE_OFFSET [] = { 0.02, 0.02, 0.005}
float minIterativeCloudPercentage
float minPlanePercentageSize
float minVarianceThForHorizontal
float maxVarianceThForHorizontal
float ransacThDistancePointShape
float ransacNormalDistanceWeigth
vector< float > horizontalAxis
vector< float > supportEdgeRemoveOffset
int ransacMaxIteration
PCLVisualizer vis
PCLCloudPtr originalCloud
PCLNormalPtr originalNorms
boost::thread vis_thread
boost::mutex vis_mutex
SACSegmentationFromNormals
*
< PointXYZ, Normal > seg
const double inf = std::numeric_limits<double>::infinity()
const double neg_inf = -std::numeric_limits<double>::infinity()
Function Documentation
PrimitiveIdxPtr createNewIdxMap (PrimitiveIdxPtr previousInliersMap, PointIndices::Ptr inliers, int level)
Definition at line 139 of file supports_segmentation_srv.cpp.
References valueBelongsToArray().
Referenced by findSupports().
ExtractIndices< PointXYZ> extract (true)
Referenced by removePlaneInliner().
bool findSupports (SupportSegmentation::Request & req, SupportSegmentation::Response & res)
Definition at line 241 of file supports_segmentation_srv.cpp.
References createNewIdxMap(), getPointOnPlane(), horizontalAxis, initializeInputParameters(), isHorizontalPlane(), maxVarianceThForHorizontal, minIterativeCloudPercentage, minPlanePercentageSize, minVarianceThForHorizontal, originalCloud, originalNorms, ransacMaxIteration, ransacNormalDistanceWeigth, ransacPlaneSegmentator(), ransacThDistancePointShape, removePlaneInliner(), and supportEdgeRemoveOffset.
Referenced by main().
PCLCloudPtr getPointOnPlane (PCLCloudPtr plane, PrimitiveIdxPtr inlierIdx, int mapLevel)
Definition at line 187 of file supports_segmentation_srv.cpp.
References inf, neg_inf, originalCloud, supportEdgeRemoveOffset, and valueBelongsToArray().
Referenced by findSupports().
void initializeInputParameters (SupportSegmentation::Request & req)
Definition at line 70 of file supports_segmentation_srv.cpp.
References DEFAULT_PARAM_SUPPORT_SRV_HORIZONTAL_AXIS, DEFAULT_PARAM_SUPPORT_SRV_MIN_ITERATIVE_CLOUD_PERCENTAGE, DEFAULT_PARAM_SUPPORT_SRV_MIN_ITERATIVE_SUPPORT_PERCENTAGE, DEFAULT_PARAM_SUPPORT_SRV_RANSAC_DISTANCE_POINT_IN_SHAPE_THRESHOLD, DEFAULT_PARAM_SUPPORT_SRV_RANSAC_MAX_ITERATION_THRESHOLD, DEFAULT_PARAM_SUPPORT_SRV_RANSAC_MODEL_NORMAL_DISTANCE_WEIGHT, DEFAULT_PARAM_SUPPORT_SRV_SUPPORT_EDGE_REMOVE_OFFSET, DEFAULT_PARAM_SUPPORT_SRV_VARIANCE_THRESHOLD_FOR_HORIZONTAL, srvm::getService3DArrayParameter(), srvm::getServiceFloatParameter(), srvm::getServiceIntParameter(), horizontalAxis, maxVarianceThForHorizontal, minIterativeCloudPercentage, minPlanePercentageSize, minVarianceThForHorizontal, ransacMaxIteration, ransacNormalDistanceWeigth, ransacThDistancePointShape, and supportEdgeRemoveOffset.
Referenced by findSupports().
bool isHorizontalPlane (PCLNormalPtr normal, ModelCoefficients::Ptr coefficients, vector< float > referimentAxis)
Definition at line 161 of file supports_segmentation_srv.cpp.
References maxVarianceThForHorizontal, and minVarianceThForHorizontal.
Referenced by findSupports().
int main (int argc, char ** argv)
Definition at line 363 of file supports_segmentation_srv.cpp.
References findSupports(), and srvm::SRV_NAME_SUPPORT_FILTER.
void ransacPlaneSegmentator (PCLCloudPtr inputCloud, PCLNormalPtr normals, PointIndices::Ptr & inlierOutput, ModelCoefficients::Ptr & coefficientOutput)
Definition at line 90 of file supports_segmentation_srv.cpp.
References ransacMaxIteration, ransacNormalDistanceWeigth, ransacThDistancePointShape, and seg.
Referenced by findSupports().
void removePlaneInliner (PCLCloudPtr inputCloud, PointIndices::Ptr & removeIndex, PCLCloudPtr output)
Definition at line 115 of file supports_segmentation_srv.cpp.
References extract().
Referenced by findSupports().
bool valueBelongsToArray (int value, PointIndices::Ptr inliers)
Definition at line 131 of file supports_segmentation_srv.cpp.
Referenced by createNewIdxMap(), and getPointOnPlane().
Variable Documentation
const float DEFAULT_PARAM_SUPPORT_SRV_HORIZONTAL_AXIS[3] = { 0.0f, 0.0f, -1.0f}
Definition at line 38 of file supports_segmentation_srv.cpp.
Referenced by initializeInputParameters().
const float DEFAULT_PARAM_SUPPORT_SRV_MIN_ITERATIVE_CLOUD_PERCENTAGE = 0.030f
Definition at line 30 of file supports_segmentation_srv.cpp.
Referenced by initializeInputParameters().
const float DEFAULT_PARAM_SUPPORT_SRV_MIN_ITERATIVE_SUPPORT_PERCENTAGE = 0.030f
Definition at line 31 of file supports_segmentation_srv.cpp.
Referenced by initializeInputParameters().
const float DEFAULT_PARAM_SUPPORT_SRV_RANSAC_DISTANCE_POINT_IN_SHAPE_THRESHOLD = 0.02f
Definition at line 35 of file supports_segmentation_srv.cpp.
Referenced by initializeInputParameters().
const int DEFAULT_PARAM_SUPPORT_SRV_RANSAC_MAX_ITERATION_THRESHOLD = 10
Definition at line 37 of file supports_segmentation_srv.cpp.
Referenced by initializeInputParameters().
const float DEFAULT_PARAM_SUPPORT_SRV_RANSAC_MODEL_NORMAL_DISTANCE_WEIGHT = 0.9f
Definition at line 36 of file supports_segmentation_srv.cpp.
Referenced by initializeInputParameters().
const float DEFAULT_PARAM_SUPPORT_SRV_SUPPORT_EDGE_REMOVE_OFFSET[] = { 0.02, 0.02, 0.005}
Definition at line 39 of file supports_segmentation_srv.cpp.
Referenced by initializeInputParameters().
const float DEFAULT_PARAM_SUPPORT_SRV_VARIANCE_THRESHOLD_FOR_HORIZONTAL = 0.09f
Definition at line 33 of file supports_segmentation_srv.cpp.
Referenced by initializeInputParameters().
vector<float> horizontalAxis
Definition at line 46 of file supports_segmentation_srv.cpp.
Referenced by callSupportFilter(), findSupports(), and initializeInputParameters().
const double inf = std::numeric_limits<double>::infinity()
Definition at line 184 of file supports_segmentation_srv.cpp.
Referenced by getPointOnPlane().
float maxVarianceThForHorizontal
Definition at line 44 of file supports_segmentation_srv.cpp.
Referenced by findSupports(), initializeInputParameters(), and isHorizontalPlane().
float minIterativeCloudPercentage
Definition at line 44 of file supports_segmentation_srv.cpp.
Referenced by findSupports(), and initializeInputParameters().
float minPlanePercentageSize
Definition at line 44 of file supports_segmentation_srv.cpp.
Referenced by findSupports(), and initializeInputParameters().
float minVarianceThForHorizontal
Definition at line 44 of file supports_segmentation_srv.cpp.
Referenced by findSupports(), initializeInputParameters(), and isHorizontalPlane().
const double neg_inf = -std::numeric_limits<double>::infinity()
Definition at line 185 of file supports_segmentation_srv.cpp.
Referenced by getPointOnPlane().
PCLCloudPtr originalCloud
Definition at line 51 of file supports_segmentation_srv.cpp.
Referenced by findSupports(), and getPointOnPlane().
PCLNormalPtr originalNorms
Definition at line 52 of file supports_segmentation_srv.cpp.
Referenced by findSupports().
int ransacMaxIteration
Definition at line 47 of file supports_segmentation_srv.cpp.
Referenced by findSupports(), initializeInputParameters(), and ransacPlaneSegmentator().
float ransacNormalDistanceWeigth
Definition at line 44 of file supports_segmentation_srv.cpp.
Referenced by findSupports(), initializeInputParameters(), and ransacPlaneSegmentator().
float ransacThDistancePointShape
Definition at line 44 of file supports_segmentation_srv.cpp.
Referenced by findSupports(), initializeInputParameters(), and ransacPlaneSegmentator().
SACSegmentationFromNormals< PointXYZ, Normal> seg
Definition at line 89 of file supports_segmentation_srv.cpp.
Referenced by ransacConeDetaction(), ransacCylinderDetaction(), ransacPlaneDetaction(), ransacPlaneSegmentator(), and ransacSphereDetection().
vector<float> supportEdgeRemoveOffset
Definition at line 46 of file supports_segmentation_srv.cpp.
Referenced by findSupports(), getPointOnPlane(), and initializeInputParameters().
PCLVisualizer vis
Definition at line 50 of file supports_segmentation_srv.cpp.
boost::mutex vis_mutex
Definition at line 54 of file supports_segmentation_srv.cpp.
boost::thread vis_thread
Definition at line 53 of file supports_segmentation_srv.cpp.